#!/bin/bash

file=$2
target="$1"

low=1
high=$(wc -l < "$file")

while [ "$low" -le "$high" ]; do
    mid=$(( (low + high) / 2 ))
    line=$(sed -n "${mid}p" "$file")

    if [ "$line" == "$target" ]; then
        exit 0
    elif [[ "$line" < "$target" ]]; then
        low=$((mid + 1))
    else
        high=$((mid - 1))
    fi
done

exit 1