#!/bin/sh

if [ "$#" -lt "1" ]
then
    echo "docm: fatal: not enough arguments (1 needed, $# supplied)" >&2
    exit 1
fi

# check if document already exists

if docm-document-exists $1
then
    echo "docm: fatal: document \"$1\" already exists" >&2
    exit 1
fi

touch .docm/docs/$1
echo "title=$1" >> .docm/docs/$1

echo "$1" >> .docm/documentlist

tmpfile=$(mktemp .docm/documentlist.XXXXXX) || exit 1
sort .docm/documentlist > "$tmpfile" && mv "$tmpfile" .docm/documentlist
