#!/bin/sh

# Usage: docm-view-document <document-name>

if [ "$#" -lt "1" ]
then
    echo "docm: fatal: not enough arguments (1 needed, $# supplied)" >&2
    exit 1
fi

if ! docm-document-exists "$1"
then
    echo "docm: fatal: document \"$1\" does not exist" >&2
    exit 1
fi

echo "$1"
if ! [ "$(docm-get-attribute "$1" file)" == "" ]
then
    echo "Files:"
    docm-get-attribute "$1" file
fi

grep "[^=]\+-to=.\+" "$(docm-get-context-dir)"/docs/"$1" | sed "s/^/--/g" | sed "s/-to=/-> /g"
grep "[^=]\+-from=.\+" "$(docm-get-context-dir)"/docs/"$1" | sed "s/^/<-/g" | sed "s/-from=/-- /g"
