#!/bin/sh
echo "Docm

Usage:
    docm make-context
    docm make-document <title>
    docm rm-document <title>
    docm cat-document <title>
    docm set-attribute <document> <name> <value>
    docm rm-attribute <document> <name> [<value>]
    docm make-link <from> <type> <to>"