#!/bin/sh

# usage: docm-rm-attribute <document-name> <attribute-name> [<attribute-content>]

if [ "$#" -lt "2" ]
then
    echo "docm: fatal: not enough arguments (2 needed, $# supplied)" >&2
    exit 1
fi

if [ "$#" = "2" ]
then
    sed -i '' "/^$2=/d" "$(docm-get-context-dir)"/docs/"$1"
else
    sed -i '' "/^$2=$3$/d" "$(docm-get-context-dir)"/docs/"$1"
fi