#!/bin/sh

# set-attribute <document> <attribute-name> <attribute-value>

if [ "$#" -lt "3" ]
then
    echo "docm: fatal: not enough arguments (3 needed, $# supplied)" >&2
    exit 1
fi

if [[ $2 == *"="* ]]
then
    echo "docm: fatal: invalid attribute name \"$2\"" >&2
    exit 1
fi

echo "$2=$3" >> .docm/docs/$1

tmpfile=$(mktemp .docm/docs/$1.XXXXXX) || exit 1
sort .docm/docs/$1 > "$tmpfile" && mv "$tmpfile" .docm/docs/$1