#!/bin/sh

if [ "$#" -lt "1" ]
then
    echo "docm: fatal: not enough arguments (1 needed, $# supplied)" >&2
    exit 1
fi

# check if document already exists

if docm-document-exists "$1"
then
    echo "docm: fatal: document \"$1\" already exists" >&2
    exit 1
fi

touch "$(docm-get-context-dir)"/docs/"$1"
echo "title=$1" >> "$(docm-get-context-dir)"/docs/"$1"

echo "$1" >> "$(docm-get-context-dir)"/documentlist

tmpfile=$(mktemp "$(docm-get-context-dir)"/documentlist.XXXXXX) || exit 1
sort "$(docm-get-context-dir)"/documentlist > "$tmpfile" && mv "$tmpfile" "$(docm-get-context-dir)"/documentlist
