#!/bin/sh

if [ "$#" -lt "1" ]
then
    cat docs/docm.txt
    exit 0
fi

while getopts ":l" option; do
    case "$option" in
        (l) ls docs
            exit 0;;
        (?) echo "docm: fatal: invalid option" >&2
            echo "use 'docm help' for an overview of Docm" >&2;;
    esac
done

if [ -e "docs/$1.txt" ]
then
    cat "docs/$1.txt"
else
    echo "docm: fatal: cannot find specified help file" >&2
    echo "For a list of available pages use 'docm help -l'" >&2
    exit 1
fi