#!/bin/sh

soption="0"

while getopts ":s" option; do
    case "$option" in
        (s) soption="1";;
        (?) echo "docm: fatal: invalid option" >&2
            echo "use 'docm help' for an overview of Docm" >&2;;
    esac
done

cat "$(docm-get-context-dir)"/documentlist | while read
do
    if [ "$soption" == "1" ]
    then
        echo "$REPLY"
    else
        docm-view-document "$REPLY"
    fi
done
